In [10]:
import numpy as np

rng = np.random.default_rng()

matrices = []
inverses = []

while len(matrices) < 3:
    M = rng.integers(-10, 11, size=(3, 3))
    if abs(np.linalg.det(M)) < 1e-9:
        continue
    matrices.append(M)
    inverses.append(np.linalg.inv(M))

for i, (M, Minv) in enumerate(zip(matrices, inverses), start = 1):
    print(f"\nMatrix",i,"\n", M)
    print(f"\nInverse of matrix #{i} (numpy):\n{Minv}")
    print(f"\nCheck M * (M inverse):\n{M @ Minv}")



Matrix 1 
 [[  3   8 -10]
 [  2  -7  -5]
 [  6   8   9]]

Inverse of matrix #1 (numpy):
[[ 0.02226525  0.14714424  0.10648596]
 [ 0.0464666  -0.08422072  0.00484027]
 [-0.05614714 -0.0232333   0.03581801]]

Check M * (M inverse):
[[ 1.00000000e+00  1.38777878e-17 -8.32667268e-17]
 [-7.63278329e-17  1.00000000e+00 -1.38777878e-17]
 [-6.93889390e-18 -3.46944695e-17  1.00000000e+00]]

Matrix 2 
 [[-10   6   2]
 [ -4   0   8]
 [  9  -9  -9]]

Inverse of matrix #2 (numpy):
[[-0.16666667 -0.08333333 -0.11111111]
 [-0.08333333 -0.16666667 -0.16666667]
 [-0.08333333  0.08333333 -0.05555556]]

Check M * (M inverse):
[[ 1.00000000e+00  1.94289029e-16  9.71445147e-17]
 [ 1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [-1.52655666e-16 -1.80411242e-16  1.00000000e+00]]

Matrix 3 
 [[ 5 -9  2]
 [ 0  0 -8]
 [ 0 -1  6]]

Inverse of matrix #3 (numpy):
[[ 0.2   -1.3   -1.8  ]
 [-0.    -0.75  -1.   ]
 [-0.    -0.125 -0.   ]]

Check M * (M inverse):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
